---
abstract: 'RT-Extension-FontAwesome Extension'
author:
  - 'NETWAYS GmbH <support@netways.de>'
build_requires:
  ExtUtils::MakeMaker: '6.59'
configure_requires:
  ExtUtils::MakeMaker: '0'
dynamic_config: 0
generated_by: 'ExtUtils::MakeMaker version 7.0401, CPAN::Meta::Converter version 2.150005'
license: gpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: RT-Extension-FontAwesome
no_index:
  directory:
    - t
    - inc
requires:
  perl: '5.010001'
version: v0.0.1
x_serialization_backend: 'CPAN::Meta::YAML version 0.018'
